steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
  - -ceu
  - |
    gcloud run deploy cb-demo \
      --image us-docker.pkg.dev/cloudrun/container/hello \
      --region asia-northeast1 \
      --platform managed \
      --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
