steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  env:
  - CLOUDSDK_CONFIG=/workspace/.gcloud_config_a
  entrypoint: 'bash'
  args:
  - -ceu
  - |
    echo "CONFIG=$CLOUDSDK_CONFIG"
    ls -ld $CLOUDSDK_CONFIG || true
    gcloud config list
    gcloud auth list
