steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  env:
  - CLOUDSDK_CONFIG=/workspace/.gcloud_config_a
  entrypoint: 'bash'
  args:
  - -ceu
  - |
    echo "CLOUDSDK_CONFIG=$$CLOUDSDK_CONFIG"
    echo "== check dir =="
    ls -ld $$CLOUDSDK_CONFIG || true
    echo "== gcloud config =="
    gcloud config list
    echo "== gcloud auth =="
    gcloud auth list

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
