steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  env:
  - CLOUDSDK_CONFIG=/workspace/.gcloud_config_a
  entrypoint: 'bash'
  args:
  - -ceu
  - |
    echo "CLOUDSDK_CONFIG=$$CLOUDSDK_CONFIG"
    echo "== mkdir config dir =="
    mkdir -p $$CLOUDSDK_CONFIG
    ls -ld $$CLOUDSDK_CONFIG
    echo "== gcloud info (check config path) =="
    gcloud info --format='value(config.paths.global_config_dir)'
    echo "== gcloud auth =="
    gcloud auth list

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
